AWSTemplateFormatVersion: 2010-09-09
Description: FinOps pipeline deployment

Resources:
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Metadata:
      Comment: Pipeline deploying the FinOps templates
    Properties:
      Name: finops
      RoleArn: !GetAtt FinOpsPipelineRole.Arn
      ArtifactStores:
        - ArtifactStore:
            Type: S3
            Location: !Ref Bucket
          Region: !Ref "AWS::Region"
      Stages:
        - Name: Source
          Actions:
            - Name: FinOpsRepository
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: 1
              Configuration:
                RepositoryName: !GetAtt Repository.Name
                BranchName: master
              OutputArtifacts:
                - Name: SourceArtifact
              Region: !Ref "AWS::Region"
        - Name: Build
          Actions:
            - Name: Artifacts
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceArtifact
              Configuration:
                ProjectName: !Ref CodeBuild
                EnvironmentVariables:
                  Fn::Sub:
                    - '[{"name":"S3Bucket","value":"${Bucket}"}]'
                    - Bucket: !Ref Bucket
              OutputArtifacts:
                - Name: MainArtifact
                - Name: ZipArtifact
        - Name: Deploy
          Actions:
            - Name: UploadToS3
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: S3
                Version: 1
              InputArtifacts:
                - Name: ZipArtifact
              Configuration:
                BucketName: !Ref Bucket
                Extract: true
              Region: !Ref "AWS::Region"
              RunOrder: 5
            - Name: MainStack
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: MainArtifact
              Configuration:
                StackName: FinOpsMainStack
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                RoleArn: !GetAtt FinOpsStackRole.Arn
                ParameterOverrides:
                  Fn::Sub:
                    - '{"S3Bucket": "${Bucket}", "Release": { "Fn::GetParam" : ["MainArtifact", "parameters.json", "release"]}}'
                    - Bucket: !Ref Bucket
                TemplatePath: MainArtifact::root.yaml
              Region: !Ref "AWS::Region"
              RunOrder: 15
